services:
  backend:
   build: ../backend
   container_name: backend
   volumes:
     - ../backend:/app
   ports:
     - "3000:3000"
   networks:
     - app-network
  angular:
    build: ../frontend
    container_name: frontend
    ports:
     - "4200:80"
    networks:
     - app-network
networks:
  app-network:
    driver: bridge